/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QuickRegexPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  rules: [
    {
      find: "(\\w+)\\s\\1",
      replace: "$1",
      flags: "gi",
      shouldProtect: false,
      toLower: false
    }
  ]
};
var QuickRegexPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "run-quick-regex-sequence",
      name: "Run Quick Regex Sequence",
      editorCallback: (editor, view) => {
        this.runPipeline(editor);
      }
    });
    this.addSettingTab(new QuickRegexSettingTab(this.app, this));
  }
  runPipeline(editor) {
    const selection = editor.getSelection();
    if (!selection) {
      new import_obsidian.Notice("No text selected!");
      return;
    }
    let modifiedText = selection;
    let errors = 0;
    for (const rule of this.settings.rules) {
      try {
        if (rule.find.length === 0) continue;
        const flags = rule.flags || "g";
        const regex = new RegExp(rule.find, flags);
        if (rule.shouldProtect) {
          modifiedText = modifiedText.replace(regex, (match, group1) => {
            if (group1) return group1;
            return "\n";
          });
        } else {
          const rawSubstitution = rule.replace.replace(/\\n/g, "\n").replace(/\\t/g, "	").replace(/\\r/g, "");
          if (rule.toLower) {
            modifiedText = modifiedText.replace(regex, (...args) => {
              const match = args[0];
              let output = rawSubstitution.replace(/\$(\d+|&)/g, (m, token) => {
                if (token === "&") return match;
                const groupIndex = parseInt(token);
                return args[groupIndex] !== void 0 ? args[groupIndex] : m;
              });
              return output.toLowerCase();
            });
          } else {
            modifiedText = modifiedText.replace(regex, rawSubstitution);
          }
        }
      } catch (e) {
        console.error(`Regex error on rule: ${rule.find}`, e);
        errors++;
      }
    }
    editor.replaceSelection(modifiedText);
    if (errors > 0) {
      new import_obsidian.Notice(`Completed with ${errors} regex errors. Check console.`);
    } else {
      new import_obsidian.Notice("Quick Regex Sequence complete.");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var QuickRegexSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Quick Regex Sequence Rules" });
    containerEl.createEl("p", {
      text: "Rules are applied in order from top to bottom. Drag the handle on the left to reorder."
    });
    containerEl.createEl("style", {
      text: `
        .qrs-header-row {
          display: flex;
          gap: 10px;
          padding: 0 10px 10px 10px;
          border-bottom: 1px solid var(--background-modifier-border);
          margin-bottom: 10px;
          font-weight: bold;
          color: var(--text-muted);
          font-size: 0.8em;
        }

        .qrs-setting-item .setting-item-control {
          justify-content: flex-start;
          width: 100%;
          gap: 10px;
        }
        .qrs-setting-item .setting-item-info {
          display: none;
        }

        /* Column Widths */
        .qrs-col-drag { width: 30px; display: flex; align-items: center; justify-content: center; cursor: grab; color: var(--text-muted); }
        .qrs-col-protect { width: 50px; display: flex; align-items: center; justify-content: center; }
        .qrs-col-lower { width: 30px; display: flex; align-items: center; justify-content: center; } /* New Column */
        .qrs-col-find { flex: 3; }
        .qrs-col-flags { flex: 1; }
        .qrs-col-replace { flex: 3; }
        .qrs-col-delete { width: 40px; text-align: right; }

        /* Make inputs fill their columns */
        .qrs-col-find, .qrs-col-flags, .qrs-col-replace {
          width: 100%;
        }

        .qrs-sortable-chosen {
          opacity: 0.5;
        }

        .qrs-help-box { margin-top: 30px; border-top: 1px solid var(--background-modifier-border); padding-top: 20px; }
        .qrs-help-summary { cursor: pointer; font-weight: bold; color: var(--text-accent); margin-bottom: 10px; }
        .qrs-help-content { padding: 10px; background: var(--background-secondary); border-radius: 5px; font-size: 0.9em; }
        .qrs-help-content table { width: 100%; }
      `
    });
    new import_obsidian.Setting(containerEl).addButton(
      (button) => button.setButtonText("Add New Rule").setCta().onClick(async () => {
        this.plugin.settings.rules.push({
          find: "",
          replace: "",
          flags: "gm",
          shouldProtect: false,
          toLower: false
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    const header = containerEl.createDiv("qrs-header-row");
    header.createDiv({ text: "", cls: "qrs-col-drag" });
    header.createDiv({
      text: "KEEP",
      cls: "qrs-col-protect",
      title: "Protect Code Blocks (Group 1)"
    });
    header.createDiv({
      text: "Aa",
      cls: "qrs-col-lower",
      title: "Convert output to Lowercase"
    });
    header.createDiv({ text: "FIND (REGEX)", cls: "qrs-col-find" });
    header.createDiv({ text: "FLAGS", cls: "qrs-col-flags" });
    header.createDiv({ text: "REPLACE", cls: "qrs-col-replace" });
    header.createDiv({ text: "", cls: "qrs-col-delete" });
    this.plugin.settings.rules.forEach((rule, index) => {
      const s = new import_obsidian.Setting(containerEl);
      s.setClass("qrs-setting-item");
      s.settingEl.setAttribute("draggable", "true");
      s.settingEl.addEventListener("dragstart", (e) => {
        if (e.dataTransfer) {
          e.dataTransfer.setData("text/plain", index.toString());
          e.dataTransfer.effectAllowed = "move";
        }
        s.settingEl.classList.add("qrs-sortable-chosen");
      });
      s.settingEl.addEventListener(
        "dragend",
        (e) => s.settingEl.classList.remove("qrs-sortable-chosen")
      );
      s.settingEl.addEventListener("dragover", (e) => {
        e.preventDefault();
        if (e.dataTransfer) e.dataTransfer.dropEffect = "move";
      });
      s.settingEl.addEventListener("drop", async (e) => {
        e.preventDefault();
        if (!e.dataTransfer) return;
        const dragIndex = parseInt(e.dataTransfer.getData("text/plain"));
        const dropIndex = index;
        if (dragIndex !== dropIndex && !isNaN(dragIndex)) {
          const movedRule = this.plugin.settings.rules[dragIndex];
          this.plugin.settings.rules.splice(dragIndex, 1);
          this.plugin.settings.rules.splice(dropIndex, 0, movedRule);
          await this.plugin.saveSettings();
          this.display();
        }
      });
      const dragHandle = s.controlEl.createDiv("qrs-col-drag");
      (0, import_obsidian.setIcon)(dragHandle, "grip-vertical");
      const protectContainer = s.controlEl.createDiv("qrs-col-protect");
      new import_obsidian.ToggleComponent(protectContainer).setValue(rule.shouldProtect || false).setTooltip("Keep Group 1, Squash others").onChange(async (value) => {
        this.plugin.settings.rules[index].shouldProtect = value;
        await this.plugin.saveSettings();
        this.display();
      });
      const lowerContainer = s.controlEl.createDiv("qrs-col-lower");
      if (!rule.shouldProtect) {
        new import_obsidian.ToggleComponent(lowerContainer).setValue(rule.toLower || false).setTooltip("Convert Replacement to Lowercase").onChange(async (value) => {
          this.plugin.settings.rules[index].toLower = value;
          await this.plugin.saveSettings();
        });
      }
      s.addText((text) => {
        text.setPlaceholder("e.g. (\\w+)").setValue(rule.find).onChange(async (value) => {
          this.plugin.settings.rules[index].find = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.addClass("qrs-col-find");
      });
      s.addText((text) => {
        text.setPlaceholder("gim").setValue(rule.flags).onChange(async (value) => {
          this.plugin.settings.rules[index].flags = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.addClass("qrs-col-flags");
      });
      if (!rule.shouldProtect) {
        s.addTextArea((text) => {
          text.setPlaceholder("Replacement").setValue(rule.replace).onChange(async (value) => {
            this.plugin.settings.rules[index].replace = value;
            await this.plugin.saveSettings();
          });
          text.inputEl.addClass("qrs-col-replace");
        });
      } else {
        const infoDiv = s.controlEl.createDiv("qrs-col-replace");
        infoDiv.setText("\u2728 Logic Active: Preserves Group 1, squashes others.");
        infoDiv.style.color = "var(--text-accent)";
        infoDiv.style.fontSize = "0.8em";
        infoDiv.style.display = "flex";
        infoDiv.style.alignItems = "center";
      }
      s.addButton((button) => {
        button.setIcon("trash").setTooltip("Delete Rule").setWarning().onClick(async () => {
          this.plugin.settings.rules.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        });
        button.buttonEl.addClass("qrs-col-delete");
      });
      s.controlEl.prepend(lowerContainer);
      s.controlEl.prepend(protectContainer);
      s.controlEl.prepend(dragHandle);
    });
    const helpContainer = containerEl.createEl("details", {
      cls: "qrs-help-box"
    });
    helpContainer.createEl("summary", {
      text: "Need Help? View Usage Guide & Regex Cheatsheet",
      cls: "qrs-help-summary"
    });
    const helpContentDiv = helpContainer.createDiv("qrs-help-content");
    this.loadHelpFile(helpContentDiv);
  }
  async loadHelpFile(targetEl) {
    try {
      const helpFilePath = `${this.plugin.manifest.dir}/cheatsheet.md`;
      const markdownContent = await this.plugin.app.vault.adapter.read(helpFilePath);
      await import_obsidian.MarkdownRenderer.render(
        this.plugin.app,
        markdownContent,
        targetEl,
        helpFilePath,
        this.plugin
      );
    } catch (error) {
      targetEl.createEl("p", {
        text: "Could not load cheatsheet.md."
      });
    }
  }
};
